apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-docker
  template:
    metadata:
      labels:
        app: spring-docker
    spec:
      containers:
        - name: app
          image: ankit741/spring-docker:v1
          ports:
            - containerPort: 8080
          env:
          imagePullPolicy: Always